export const LOADING_PRODUCTS_STORAGE = 'shoppingCart:LOADING_PRODUCTS_STORAGE'
export const ADD_ITEM_CART = 'shoppingCart:ADD_ITEM_CART'
export const REMOVE_ITEM_CART = 'shoppingCart:REMOVE_ITEM_CART'
export const ADD_QNTD = 'shoppingCart:ADD_QNTD'
export const REMOVE_QNTD = 'shoppingCart:REMOVE_QNTD'